steps:
  - id: Terraform Init
    name: hashicorp/terraform:latest
    entrypoint: sh
    args:
      - -c
      - |
        terraform init

  - id: Terraform Execute
    name: hashicorp/terraform:latest
    entrypoint: sh
    args:
      - -c
      - |
        if [ "${_TF_ACTION}" = "destroy" ]; then

          if [ "${_CONFIRM_DESTROY}" != "YES" ]; then
            echo "ERROR: Destroy blocked."
            echo "To destroy, set:"
            echo "_TF_ACTION=destroy"
            echo "_CONFIRM_DESTROY=YES"
            exit 1
          fi

          echo "Starting Terraform Destroy..."
          terraform destroy -auto-approve

        else

          echo "Starting Terraform Apply..."
          terraform apply -auto-approve

        fi

substitutions:
  _TF_ACTION: "apply"
  _CONFIRM_DESTROY: "NO"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"
