pipeline {
    agent any
    stages {
        stage('git clone') {
            steps {
                echo 'cloning repo'
            }
                
          }
        stage('maven build') {
            steps {
                echo 'build maven'
            }
          } 
        stage('deploy app in tomcall') {
            steps {
                echo 'deploy app in tomecat'
            }
         }
        post {
            always {
                echo 'cleaning up'
            }
        }

       }
    }
